Add : [Programmers-12918] 문자열 다루기 기본
Jjiggu/CodingTest pull request #21
Opened 2024-08-08 14:42 UTC by Ju0011

## ☄️ 이슈 번호
#19 
## 🔗 문제 번호 
12917, 12918, 12950, 82612
## 🤷 어려웠던 문제
12918
## 🤩 해결 방안
문자열의 길이가 4혹은 6이라고 했는데 답은 in (4,6)으로 제출해야 되었다.
문제 해석이 중요한거 같다.
## 📰 Reference
https://velog.io/@cha-suyeon/Python-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%8B%A4%EB%A3%A8%EA%B8%B0-%EA%B8%B0%EB%B3%B8lv.1

2024-08-08 15:37 UTC, Jjiggu commented on 주영/프로그래머스/1/12918. 문자열 다루기 기본/문자열 다루기 기본.py
> +    return s.isdigit() and len(s) in (4, 6)
try catch 사용하여 풀어보는것도 추천드립니다!

2024-08-08 15:37 UTC, Jjiggu commented on 주영/프로그래머스/1/12950. 행렬의 덧셈/행렬의 덧셈.py
> +    return arr1
numpy 사용하면 좀 더 편하게 풀 수 있습니다! 
하지만 문제에서 원하는 풀이 방식은 위와 같은 코드가 맞는것 같아요 :)

2024-08-08 15:37 UTC, Jjiggu commented on 주영/프로그래머스/1/82612. 부족한 금액 계산하기/부족한 금액 계산하기.py
> +        sum = sum + price * i
sum += price * i로 작성하는것이 좋을 것 같습니다~

2024-08-08 15:45 UTC, Jjiggu requested changes
해당 부분만 수정하면 될 것 같습니다!
수고하셨습니다 👍

2024-08-09 14:06 UTC, Jjiggu approved these changes
수고하셨습니다 :)

2024-08-09 14:11 UTC, seobokyeong0314 commented
늦어서 죄송해요ㅠㅠ 수고하셨습니다!

2024-08-09 14:20 UTC, seobokyeong0314 approved these changes

2024-08-09 14:21 UTC, seobokyeong0314 approved these changes

2024-08-09 14:21 UTC, seobokyeong0314 approved these changes

2024-08-10 11:22 UTC, merged