Add : [Programmers-131705] 삼총사
Jjiggu/CodingTest pull request #30
Opened 2024-08-10 11:45 UTC by Ju0011

## ☄️ 이슈 번호
#29 

## 🔗 문제 번호 
12930, 131705, 147355, 68935

## 🤷 어려웠던 문제
68935

## 🤩 해결 방안
3진법이 생소해서 조금 해맸다. 결국 3진법의 정의를 다시 찾아보고 고민했다.

## 📰 Reference
https://velog.io/@code_angler/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%A7%84%EC%88%98%EB%B3%80%ED%99%982%EC%A7%84%EB%B2%95-3%EC%A7%84%EB%B2%95-5%EC%A7%84%EB%B2%95-10%EC%A7%84%EB%B2%95n%EC%A7%84%EB%B2%95

2024-08-10 12:50 UTC, Jjiggu requested changes

2024-08-10 12:50 UTC, Jjiggu commented on 주영/프로그래머스/1/12930. 이상한 문자 만들기/이상한 문자 만들기.py
> +            if j % 2 == 0:
비트 연산자를 사용해서 짝수 홀수 구분 하는 방법이 있다고 해서 공유드립니다!
```
if j&1==0:
```

2024-08-10 12:50 UTC, Jjiggu commented on 주영/프로그래머스/1/131705. 삼총사/삼총사.py
> +    return answer
itertools의 combinations 모듈을 사용하면 좀 더 간단하게 풀 수 있을 것 같습니다!

2024-08-10 12:50 UTC, Jjiggu commented on 주영/프로그래머스/1/147355. 크기가 작은 부분문자열/크기가 작은 부분문자열.py
> +            answer += 1
코드를 다음과 같이 변경하면 for문 하나 줄일 수 있을 것 같아요~!!
``` suggestion
    for i in range(len(t)-n+1):
        a.append(t[i:i+n])
        if int(t[i:i + n]) <= int(p):
           answer += 1
```

2024-08-10 12:54 UTC, Jjiggu commented on 주영/프로그래머스/1/131705. 삼총사/삼총사.py
> +    return answer
itertools의 combinations 모듈을 사용하면 좀 더 간단하게 풀 수 있을 것 같습니다!

2024-08-10 12:55 UTC, Jjiggu commented on 주영/프로그래머스/1/12930. 이상한 문자 만들기/이상한 문자 만들기.py
> +            if j % 2 == 0:
비트 연산자를 사용해서 짝수 홀수 구분 하는 방법이 있다고 해서 공유드립니다!

if j&1==0:

2024-08-10 12:56 UTC, Jjiggu reviewed
수고하셨습니다!

2024-08-10 16:58 UTC, seobokyeong0314 approved these changes

2024-08-11 06:00 UTC, Jjiggu approved these changes

2024-08-11 14:02 UTC, merged