[1주차] 보경_3일차
Jjiggu/CodingTest pull request #34
Opened 2024-08-11 05:55 UTC by seobokyeong0314

## ☄️ 이슈 번호
#33 

## 🔗 문제 번호 
12910, 86051, 12935, 12948, 12903, 12922, 70128, 77884, 12916, 12925, 76501, 12917, 82612, 12918, 12950

## 🤷 어려웠던 문제
문자열 다루기 기본(12918)

## 🤩 해결 방안
for문으로 문자열 안을 모두 탐색하는 것보다 isdigit() 함수를 쓰기*

## 📰 Reference
https://velog.io/@code_angler/%ED%8C%8C%EC%9D%B4%EC%8D%ACPython-%EB%AC%B8%EC%9E%90%EC%88%AB%EC%9E%90%EC%9D%B8%EC%A7%80-%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0isalpha-isdigit-isalnum

2024-08-11 12:18 UTC, Jjiggu requested changes

2024-08-11 12:18 UTC, Jjiggu commented on 보경/프로그래머스/1/12910. 나누어 떨어지는 숫자 배열/나누어 떨어지는 숫자 배열.py
> +    return answer
아래 코드가 조금 더 가독성이 좋을것 같은데 어떻게 생각하시나요?!
``` suggestion
   if len(answer) == 0:
        return [-1]
    else:
        return answer.sort()  # sorted(answer)
```

2024-08-11 12:18 UTC, Jjiggu commented on 보경/프로그래머스/1/12917. 문자열 내림차순으로 배치하기/문자열 내림차순으로 배치하기.py
> +    return answer
"".join을 사용하면 반복문 없이 문자열로 변환이 가능합니다!
``` suggestion
    return "".join(sorted(s, reverse = True))
```

2024-08-11 12:18 UTC, Jjiggu commented on 보경/프로그래머스/1/86051. 없는 숫자 더하기/없는 숫자 더하기.py
> +            num_lst.remove(i)
문제 제약사항에 "0 ≤ numbers의 모든 원소 ≤ 9" 라는 조건이 있어서 if 문은 없어도 될 것 같습니다!
``` suggestion
        num_lst.remove(i) 
```

2024-08-11 12:20 UTC, Jjiggu commented on 보경/프로그래머스/1/12950. 행렬의 덧셈/행렬의 덧셈.py
> +    return answer
numpy를 사용한 행렬 연산도 살펴보면 좋을것 같습니다!

2024-08-11 12:20 UTC, Jjiggu commented
수고하셨습니다 :)

2024-08-12 00:43 UTC, Ju0011 approved these changes

2024-08-12 17:36 UTC, merged